easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
        Client: 
            class: App\Entity\Client
        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController
            